---
- name: Create a directory
  ansible.builtin.file:
    path: "{{ vector_dir }}"
    state: directory
    mode: '0755'
  check_mode: false
  tags:
    - vector
- name: Download
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.27.0/vector-0.27.0-1.{{ vector_arch }}.rpm"
    dest: "{{ vector_dir }}/vector-0.27.0-1.{{ vector_arch }}.rpm"
  check_mode: false
  tags:
    - vector
- name: Install package
  become: true
  ansible.builtin.yum:
    name:
      - "{{ vector_dir }}/vector-0.27.0-1.{{ vector_arch }}.rpm"
  tags:
    - vector
- name: Start vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true
  check_mode: false
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - vector