---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: centos_7
    image: pycontribs/centos:7
    command: /usr/sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #- name: centos_8
    #image: quay.io/centos/centos:stream8
    #command: /sbin/init
provisioner:
  name: ansible
  options:
    vvv: true
    D: true
  inventory:
    hosts:
      all:
    group_vars:
      all:
        #vector_dir: "./vector2"
        vector_dir: "/tmp/vector"
    host_vars:
      centos_7:
      #ansible_user: ansible
  playbooks:
    #    create: create.yml
    converge: converge.yml
#    destroy: destroy.yml
#  hosts: ../resources/inventory/hosts.yml
#  group_vars: ../resources/inventory/group_vars/
#  host_vars: ../resources/inventory/host_vars/
verifier:
  name: ansible
#  playbooks:
#    verify: verify.yml