---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
#  - name: centos_7
#    image: pycontribs/centos:7
#    command: /usr/sbin/init
    #pre_build_image: false
#    capabilities:
#      - SYS_ADMIN
#    tmpfs:
#      - /run
#      - /tmp
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro

#  - name: centos_8
#    image: quay.io/centos/centos:stream8
    #pre_build_image: false
#    command: /sbin/init
#    capabilities:
#      - SYS_ADMIN
#    tmpfs:
#      - /run
#      - /tmp
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: debian_stretch
    image: debian:stretch
    #dockerfile: ../resources/Dockerfile.j2
    # pre_build_image: true
    #command: /sbin/init
    #command: sleep 6666
    privileged: true
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
#    env:
#      ANSIBLE_USER: ansible
#      SUDO_GROUP: sudo
#      DEPLOY_GROUP: deployer
#      container: docker

#  - name: debian
#    image: pycontribs/ubuntu:latest
    #command: "/lib/systemd/systemd"
    #pre_build_image: false
#    privileged: true
#    capabilities:
#      - SYS_ADMIN
#    tmpfs:
#      - /run
#      - /tmp
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup
provisioner:
  name: ansible
  options:
    vvv: true
    D: true
  inventory:
    hosts:
      all:
    group_vars:
      all:
        vector_dir: "/tmp/vector"
    host_vars:
      centos_7:
      #ansible_user: ansible
  playbooks:
    #    create: create.yml
    converge: converge.yml
#    destroy: destroy.yml
#  hosts: ../resources/inventory/hosts.yml
#  group_vars: ../resources/inventory/group_vars/
#  host_vars: ../resources/inventory/host_vars/
verifier:
  name: ansible
#  playbooks:
#    verify: verify.yml